= Red Hat JBoss Fuse Integration Services 
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:

toc::[]

== Overview
Red Hat JBoss Fuse Integration Services is a containerized xPaaS image that is designed for use with OpenShift. It allows developers to quickly deploy applications in a hybrid cloud environment. In Fuse Integration Services application runtime is dynamic. 

[IMPORTANT]
There are significant differences in supported configurations and functionality in the Fuse Integration Services compared to the standalone JBoss Fuse product. 

=== Differences Between the Fuse Integration Services and the JBoss Fuse Standalone release
There are several major functionality differences:

* The Karaf shell is available only at build time and can be enabled after adding ssh and shell features. You can use `*oc rsh <podId>`* and `*/deployments/karaf/bin/client`* inside the container shell to connect to the Karaf shell. 
+
[NOTE]
You can use Karaf shell only for debugging purposes as any runtime change, for example pod restart, scaling, does not persist.
* Administration views are available through OpenShift Web Console with Hawtio plugin. 
* All applications are packaged as Docker images for OpenShift.
* Kubernetes REST API is used to orchestrate the containers.

== Using Fuse Integration Services 
You can start using Fuse Integration Services by creating application and deploying it to OpenShift. There are two main ways to create an application in Fuse Integration Services:

* Using Maven Archetypes 
* Using Application Templates 

=== Using Maven Archetypes
Creates a new project based off a Maven application template created through Archetype catalog. This catalog provides examples
of Java and Karaf projects and supports s2i and local image build workflows. 

==== Maven Archetypes Catalog:
The Maven Archetype catalog has is pre-built with following examples: 

|=== 

| cdi-camel-http-archetype | Creates a new Camel route using CDI in a standalone Java Container calling the remote camel-servlet quickstart

| cdi-cxf-archetype | Creates a new CXF JAX-RS using CDI running in a standalone Java Container

| cdi-camel-archetype | Creates a new Camel route using CDI in a standalone Java Container

| cdi-camel-jetty-archetype | Creates a new Camel route using CDI in a standalone Java Container using Jetty as HTTP server

| java-simple-mainclass-archetype | Creates a new Simple standalone Java Container (main class) 

| java-camel-spring-archetype | Creates a new Camel route using Spring XML in a standalone Java container

| karaf-cxf-rest-archetype | Creates a new RESTful WebService Example using JAX-RS

| karaf-camel-rest-sql-archetype | Creates a new Camel Example using Rest DSL with SQL Database

| karaf-camel-log-archetype | Creates a new Camel Log Example

|=== 

You can select the the example that can best serve your purpose to create an application. 

==== Simple Workflow to create an application from Maven Archetype Catalog

. Use Maven archetype catalog to create a sample project with the required resources. For example, following command will create a sample project: 
+
----
$ mvn archetype:generate -Darchetype-catalog=archetype-catalog.xml 
----

. This will create a maven project with necessary dependencies. Maven properties and plugins that are used to create Docker images are added to the `*pom.xml*`. 

+

* Maven docker variables
+
|=== 

| dockerHost (docker.host) | Use this variable to specify the URL that your Docker Daemon is listening to. If this option is not set, `*DOCKER_HOST*` environment variable will be evaluated. If this is also not set, the plugin will use *`unix:///var/run/docker.sock*` as a default. 

| apiVersion (docker.apiVersion) | Use this variable if you are using older version of docker not compatible with the current version.

| image (docker.image) | Use this variable to restrict the operation of maven plugin goals. The value can be a single image name (either its alias or full name) or it can be a comma separated list with multiple image names. 

| registry (docker.registry) | Use this variable to specify globally a registry to use for pulling and pushing images.

| sourceDirectory (docker.source.dir) | Use this variable to specify the default directory that contains the assembly descriptors used by the plugin. The default value is *`src/main/docker*`. This option is only relevant for the docker:build goal.

| outputDirectory (docker.target.dir) | Use this variable to specify the default output directory to be used by the plugin. The default value is target/docker and is only used for the goal docker:build. 

|=== 

. Build and push the project to OpenShift. You can use maven goals for building and pushing docker images. 

+
|=== 

| docker:build | Builds the docker image for your maven project. 

| docker:push | Pushes the locally built docker image to the global or a local docker registry. 

| fabric8:json | Generates kubernetes JSON file for your maven project. 

| fabric8:apply | Applies the kubernetes JSON file to the current Kubernetes environment and namespace. 

|=== 
+

There are few pre-configured maven profiles that you can use to build the project. These profiles are combinations of above maven goals that simplify the build process. 

+
|=== 

| mvn -Pf8-build | Comprises of docker:build and fabric8:json. This will build dockerfile and JSON template for a project.

| mvn -Pf8-local-deploy | Comprises of docker:build, fabric8:json, and fabric8:apply. This will create docker and JSON templates and then apply them to OpenShift. 

| mvn -Pf8-deploy: | Comprises of docker:build, fabric8:json, docker:push, and fabric8:apply. This will create docker and JSON templates, push them to docker registry and apply to OpenShift. 

|=== 
+
In this example, we will build it locally by running the command: 
+
----
$ mvn -Pf8-local-deploy 
----
. Login to OpenShift Web Console. A pod is created for the newly created application. You can view the status of this pod, deployments and services that the application is creating. 

=== Using Application Templates 
Applications are created through OpenShift Admin Console and CLI using application templates. If you have a JSON or YAML file that defines a template, you can upload the template to the project using the CLI. This saves the template to the project for repeated use by users with appropriate access to that project. You can add the remote Git repository location to the template using template parameters. This allows you to pull the application source from remote repository and built using source-to-image (s2i) method.

. Create an application template using command *`mvn archetype:generate*`. To create an application, upload the template to your current project’s template library with the following command:

+
----
$ oc create -f quickstart-template.json -n <project>
----

. The template is now available for selection using the web console or the CLI. 

. Login to OpenShift Web Console. In the desired project, click *`Add to Project*` to create the objects from an uploaded template.

. Select the template from the list of templates in your project or from the global template library.

. Edit template parameters and then click *`Create*`. After successful creation of the application, you can view the status of application by clicking *`Pods*` tab or by running the following command:

+
----
$ oc get pods
---- 
+ 
For example, template parameters for an camel-spring quickstart are:
+
|===

| APP_NAME | Enter Application name. 

| GIT_REPO | Enter Git Repository location. This is manadatory field. 

| GIT_REF | Default value is master. This is git ref which is used to build application. 

| SERVICE_NAME | Exposed service name 

| BUILDER_VERSION | Builder version

| APP_VERSION | Application version

| MAVEN_ARGS | Default value is package-DskipTests-e. Enter arguments that are passed to mvn in the build.

| MAVEN_ARGS_APPEND | Extra arguments passed to mvn, for example multi-module builds

| ARTIFACT_DIR | MAven build directory

| BUILD_SECRET | generated if empty. The secret needed to trigger a build.

|=== 

For more information, see https://docs.openshift.com/enterprise/3.0/dev_guide/templates.html[*Application Templates*]

=== Developing Applications 
==== Injecting Kubernetes services into applications

You can inject Kubernetes services into applications by labeling the pods and use those labels to select the required pods to provide a logical service. These labels are simple key, value pairs.

===== CDI injection

Fabric8 provides a CDI extension that you can use to inject Kubernetes resources into your applications. To use the CDI extension, first add the dependency to the project's *`pom.xml*`.

----
<dependency>
  <groupId>io.fabric8</groupId>
  <artifactId>fabric8-cdi</artifactId>
  <version>{$fabric8.version}</version>
</dependency>
----

Next step is to identify the field that requires the service and then inject the service by adding a *`@ServiceName*` annotation to it. For example, 

----
@Inject
@ServiceName("my-service")
private String service.
----

The *`@PortName*` annotation is used to select a specific port by name when multiple ports are defined for a service. 


===== Using environment variables as properties

You can use to access a service by using environment variables to expose the fixed IP address and port. These are, *`SERVICE_HOST*` and *`SERVICE_PORT*`. *`SERVICE_HOST*` is the host (IP) address of the service and *`SERVICE_PORT*` is the port of the service. 
